apiVersion: v1
kind: Service
metadata:
  name: rollout-active
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-preview
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
